CREATE DATABASE ITSOL;
USE ITSOL;

CREATE TABLE NHACUNGCAP (
	maCongTy NVARCHAR(10) NOT NULL,
    tenCongTy NVARCHAR(40) NOT NULL,
    tenGiaoDich NVARCHAR(30) NULL,
    diaChi NVARCHAR(60) NULL,
    dienThoai NVARCHAR(20) NULL,
    fax NVARCHAR(20) NULL,
    email NVARCHAR(50) NULL,
    CONSTRAINT pk_NHACUNGCAP PRIMARY KEY (maCongTy)
);
CREATE TABLE LOAIHANG (
	maLoaiHang int NOT NULL,
    tenLoaiHang NVARCHAR(15) NOT NULL,
    CONSTRAINT pk_LOAIHANG PRIMARY KEY (maLoaiHang)
);
CREATE TABLE MATHANG (
	maHang NVARCHAR(10) NOT NULL,
    tenHang NVARCHAR(50) NOT NULL,
    maCongTy NVARCHAR(10) NOT NULL,
    maLoaiHang INT NOT NULL,
    soLuong INT NULL,
    donViTinh NVARCHAR(20) NULL,
    giaHang DECIMAL(10, 2) NULL,
    CONSTRAINT pk_MATHANG PRIMARY KEY (maHang),
    CONSTRAINT fk_MATHANG_LOAIHANG foreign key (maLoaiHang) REFERENCES LOAIHANG(maLoaiHang) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_MATHANG_NHACUNGCAP foreign key (maCongTy) REFERENCES NHACUNGCAP(maCongTy) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE KHACHHANG (
	maKhachHang NVARCHAR(10) NOT NULL,
    tenCongTy NVARCHAR(50) NOT NULL,
    tenGiaoDich NVARCHAR(30) NOT NULL,
    diaChi NVARCHAR(50) NULL,
    email NVARCHAR(30) NULL,
    dienThoai NVARCHAR(15) NULL,
    fax NVARCHAR(15) NULL,
    CONSTRAINT pk_KHACHHANG PRIMARY KEY (maKhachHang)
);
CREATE TABLE NHANVIEN (
	maNhanVien NVARCHAR(10) NOT NULL,
    ho NVARCHAR(20) NOT NULL,
    ten NVARCHAR(10) NOT NULL,
    ngaySinh DATETIME NULL,
    ngayLamViec DATETIME NULL,
    diaChi NVARCHAR(50) NULL,
    dienThoai NVARCHAR(15) NULL,
    luongCoBan DECIMAL(10, 2) NULL,
    phuCap DECIMAL(10, 2) NULL,
    CONSTRAINT pk_NHANVIEN PRIMARY KEY (maNhanVien)
);
CREATE TABLE DONDATHANG (
	soHoaDon INT NOT NULL,
    maKhachHang NVARCHAR(10) NOT NULL,
    maNhanVien NVARCHAR(10) NOT NULL,
    ngayDatHang DATETIME NULL,
    ngayGiaoHang DATETIME NULL,
    ngayChuyenHang DATETIME NULL,
    noiGiaoHang NVARCHAR(50) NULL,
    CONSTRAINT pk_DONDATHANG PRIMARY KEY (soHoaDon),
    CONSTRAINT fk_DONDATHANG_KHACHHANG foreign key (maKhachHang) REFERENCES KHACHHANG(maKhachHang) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_DONDATHANG_NHANVIEN foreign key (maNhanVien) REFERENCES NHANVIEN(maNhanVien) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE CHITIETDATHANG (
	soHoaDon INT NOT NULL,
    maHang NVARCHAR(10) NOT NULL,
    giaBan DECIMAL(10, 2) NOT NULL,
    soLuong SMALLINT NOT NULL,
    mucGiamGia REAL NOT NULL,
    CONSTRAINT pk_CHITIETDATHANG PRIMARY KEY (soHoaDon, maHang),
    CONSTRAINT fk_CHITIETDATHANG_DONDATHANG foreign key (soHoaDon) REFERENCES DONDATHANG(soHoaDon) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_CHITIETDATHANG_MATHANG foreign key (maHang) REFERENCES MATHANG(maHang) ON DELETE CASCADE ON UPDATE CASCADE
);

